### ISSUE TITLE
how to get cocrdinates of segmented area

### ISSUE THREAD

**Issue by hitha-assert** [RizwanMunawar/yolov7-segmentation#11]
Hi..
I want to calculate the inner area of detected segments..how to get the coordinates of polygonal segmented area..dont want the xywh 2d box co ordinates..
Thanks !

**Comment by RizwanMunawar** [comment]
@hitha-assert! The save-txt module is added for segmentation. You can use the mentioned command below to get coordinates of segmented area.
`python3 segment/predict.py --weights yolov7-seg.pt --source "videopath.mp4" --save-txt`

I am closing this issue, because the module is completed. Feel free to open new issue if you will face any problems.
