### ISSUE TITLE
Tutorial missing weights and repo missing yolov7-seg.yaml

### ISSUE THREAD

**Issue by magedhelmy1** [RizwanMunawar/yolov7-segmentation#12]
The weights are missing in the README. 

`python3 segment/train.py --data data/custom.yaml --batch 4 --weights yolov7-seg.pt --cfg yolov7-seg.yaml --epochs 10 --name yolov7-seg --img 640 --hyp hyp.scratch-high.yaml`

instead of 

`python3 segment/train.py --data data/custom.yaml --batch 4 --weights '' --cfg yolov7-seg.yaml --epochs 10 --name yolov7-seg --img 640 --hyp hyp.scratch-high.yaml`

Another thing, I think the `cfg yolov7-seg.yaml` in the repo

**Comment by RizwanMunawar** [comment]
@magedhelmy1. Yes the weights file link I have added now, but "yolov7-seg.yaml" not needed, because I have added and explain the steps to develop custom.yaml file for training.

For more details, you can take a look at the link mentioned below.
https://medium.com/augmented-startups/train-yolov7-segmentation-on-custom-data-b91237bd2a29

**Comment by magedhelmy1** [comment]
Thank you!

**Comment by RizwanMunawar** [comment]
@magedhelmy1 I am closing this issue, feel free to open a new issue if you will face any problems.
