### ISSUE TITLE
About custom data

### ISSUE THREAD

**Issue by mqbin** [RizwanMunawar/yolov7-segmentation#5]
Hi @RizwanMunawar, 
I want to try the segmentation task on my own dataset, but I encounter the following error.
```
anaconda3/envs/py39/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
```
```
yolov7-segmentation/utils/segment/dataloaders.py", line 167, in __getitem__
    masks = (torch.from_numpy(masks) if len(masks) else torch.zeros(1 if self.overlap else nl, img.shape[0] //
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```
I customize the dataset image size to be 256*256 and the format is that of the COCO dataset. For training I used the tool [JSON2YOLO](https://github.com/ultralytics/JSON2YOLO) to convert it to YOLO data format and then I got the error, how do I fix this?

The same data works fine for the detection task, but it will be wrong for the segmentation task.
The data format is as follows
```
5 0.253906 0.982422 0.226562 0.978516 0.216797 0.957031 0.246094 0.951172 0.259766 0.96875 0.253906 0.982422
```
Could you help me with this problem, thanks

**Comment by RizwanMunawar** [comment]
@mqbin! I have not converted the dataset with [JSON2YOLO](https://github.com/ultralytics/JSON2YOLO). I had labeled the dataset on roboflow, but I had selected the **instance segmentation** option, instead of **semantic segmentation.** Once you will complete the labeling in instance segmentation format, export data and just run training. You will not need to convert data with convertor [JSON2YOLO](https://github.com/ultralytics/JSON2YOLO), it will be in YOLO format directly.
For a better understanding, you can take a look at my [medium](https://medium.com/@chr043416) article **[Train YOLOv7 Segmentation on Custom Data](https://chr043416.medium.com/train-yolov7-segmentation-on-custom-data-b91237bd2a29)**

**Comment by mqbin** [comment]
Thank you for your reply.
I appreciate the information and advice you provided and I will check out the information.
