### ISSUE TITLE
How can I get a heat map for each class on this?

### ISSUE THREAD

**Issue by acsgn95** [RizwanMunawar/yolov7-segmentation#57]
I want to prepare a heat map for each class. Are there anybody know it? I trained a model, I can segment very well but, I need to create grad cam or head map for each class!!!

@RizwanMunawar

**Comment by RizwanMunawar** [comment]
@acsgn95 you can check the eigencam algorithm at the mentioned link below.
https://github.com/jacobgil/pytorch-grad-cam/tree/master

**Comment by RizwanMunawar** [comment]
@acsgn95 I am closing this issue for now. Because this is the question. It is not something related to existing implementation or error in code. For discussion, I will recommend posting your queries in the [discussion](https://github.com/RizwanMunawar/yolov7-segmentation/discussions) section. Thanks

**Comment by acsgn95** [comment]
@RizwanMunawar thanks for you attend this. But, I found a solution for this. I used your suggestion and will share something!!!
