### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.dataloaders'

### ISSUE THREAD

**Issue by Fazyl03** [RizwanMunawar/yolov7-segmentation#8]
Traceback (most recent call last):
  File "C:\Users\fazyl\Desktop\yolov7-segmentation\segment\predict.py", line 23, in <module>
    from models.common import DetectMultiBackend
  File "C:\Users\fazyl\Desktop\yolov7-segmentation\models\common.py", line 24, in <module>
    from utils.dataloaders import exif_transpose, letterbox
ModuleNotFoundError: No module named 'utils.dataloaders'

This error happening when I tried train and predict in my conda environment(without creating new env as you recommended). Can you please help with that?

**Comment by Fazyl03** [comment]
Also virtual env that I created can't see my cuda device.

**Comment by RizwanMunawar** [comment]
@Fazyl03! Did you followed all steps that I have mentioned in readme? If you have not followed all steps, then make sure to follow all steps.
https://github.com/RizwanMunawar/yolov7-segmentation/blob/main/README.md

In general, utils folder has been include dataloaders.py file, so I dont think there will be any issue that will come. Maybe you are facing this issue due to path configuration etc. Can you share the picture of terminal that include errors message that you faced?

**Comment by tsssiva** [comment]
@Fazyl03 Faced the same issue when I ran it without creating a new env. In my case, I had a 3rd party utils package installed from pypi and it was taking precedence over the local utils folder.
"pip uninstall utils -y" solved it for me.

**Comment by RizwanMunawar** [comment]
@Fazyl03! I hope the issue will solve from above comment. I am closing the issue for now, If you have any queries or issues, feel free to open new issue.

> @Fazyl03 Faced the same issue when I ran it without creating a new env. In my case, I had a 3rd party utils package installed from pypi and it was taking precedence over the local utils folder. "pip uninstall utils -y" solved it for me.
