### ISSUE TITLE
how to get the coordinates of segmented area?

### ISSUE THREAD

**Issue by deep876** [RizwanMunawar/yolov7-segmentation#9]
Hello.

I tried enabling "save_txt" option and it would give me this:

result.txt ( Line 170 in segment/predict.py )
0 0.406728 0.598982 0.237003 0.593891
0 0.61659 0.608032 0.303517 0.765837
0 0.519495 0.388575 0.204128 0.553167
0 0.21789 0.597851 0.186544 0.528281

I think these coordinates will be the xywh of 2d box

However, I want to get the coordinates of segmented area instead of 2d box coordinates. 

It will be really helpful for me if anyone can help me with this!

Thank you!

**Comment by RizwanMunawar** [comment]
@deep876! The save-txt module is added for segmentation. You can use the mentioned command below to get coordinates of segmented area.
`python3 segment/predict.py --weights yolov7-seg.pt --source "videopath.mp4" --save-txt`

I am closing this issue, because the module is completed. Feel free to open new issue if you will face any problems.
